const mongoose = require('mongoose')
const Service = new mongoose.Schema({
    _id:mongoose.Types.ObjectId,
    uid:mongoose.Types.ObjectId,
    title:String,
    description:String,
    catagory:{
        type:mongoose.Types.ObjectId,
        ref:'catagory'
    },
    subcatagory:{
        type:mongoose.Types.ObjectId,
        ref:'subcatagory'
    },
    tags:{
        type:[{
            type:String
        }]
    },
    pricing:{
        type:{
            basic:{
                title:String,
                description:String,
                deliver:Number,
                numberofscreen:Number,
                prototype:Boolean,
                revisions:Number,
                price:Number
            },
            standard:{
                title:String,
                description:String,
                deliver:Number,
                numberofscreen:Number,
                prototype:Boolean,
                revisions:Number,
                price:Number
            },
            premium:{
                title:String,
                description:String,
                deliver:Number,
                numberofscreen:Number,
                prototype:Boolean,
                revisions:Number,
                price:Number
            }
        }
    },questions:{
        type:[{
                type:String
            }]
    },faq:{
        type:String
    },imgs:{
        type:[{
            type:String
        }]
    },
    docs:{
        type:[{
            type:String
        }]
    },
    status:{
        type:String,
        num:['active','pause','panding','draft','rejected'],
        default:'draft'
    }

},{
    timestamps:true
})

module.exports = mongoose.model('services',Service)